name: bmi_calculator
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.1.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  animated_splash_screen: ^1.3.0
  flutter_screenutil: ^5.9.0
  google_fonts: ^6.1.0
  toggle_switch: ^2.1.0
  syncfusion_flutter_sliders: ^23.2.6
  syncfusion_flutter_core: ^23.2.6
  syncfusion_flutter_gauges: ^23.2.6
  intl: ^0.18.1
  page_transition: ^2.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
flutter:
  uses-material-design: true
  assets:
    - assets/images/
flutter_intl:
  enabled: true
